name: build the things

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  check-numpy-import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v22

      - name: Install Python 3.11 with Nix
        run: nix build

      - name: Install Python 3.11 with Nix
        run: nix --extra-experimental-features nix-command --extra-experimental-features flakes run nixpkgs#python311 -- -m venv .venv --copies

      - name: Install numpy
        run: .venv/bin/pip install numpy opencv-python

      - name: Fix numpy import issue
        run: ls -lah

      - name: Fix numpy import issue
        run: ./fix-python --venv .venv --libs ./gl.nix

      - name: Check numpy import after fix
        run: .venv/bin/python -c 'import numpy'


      - name: Check numpy import after fix
        run: .venv/bin/python -c 'import cv2'
